import {useState,useEffect} from 'react';
import {onAuthStateChanged,signOut} from 'firebase/auth';
import {collection,query,orderBy,onSnapshot,addDoc,serverTimestamp,updateDoc,arrayUnion,arrayRemove,doc,deleteDoc,setDoc,getDoc} from 'firebase/firestore';
import {auth,db} from './firebase';
import AuthPage from './components/Auth';
type Post={id:string;text:string;image:string;videoUrl:string;userName:string;likeCount:number;likes:string[];userId:string;mediaType:string;comments?:any[]};
const CLOUD="bvvoprge"; const PRESET="onefeed_preset"; const ADMIN="siw777513@gmail.com";
function FeedApp({onLogout}:{onLogout:()=>void}){
 const [posts,setPosts]=useState<Post[]>([]); const [tab,setTab]=useState('Feed'); const [bot,setBot]=useState('Home');
 const [show,setShow]=useState(false); const [ct,setCt]=useState<'feed'|'short'|'story'>('feed');
 const [txt,setTxt]=useState(''); const [media,setMedia]=useState(''); const [up,setUp]=useState(false);
 const [cmt,setCmt]=useState(''); const [openC,setOpenC]=useState<string|null>(null); const [q,setQ]=useState('');
 const [viewId,setViewId]=useState<string|null>(null); const [viewName,setViewName]=useState(''); const [pTab,setPTab]=useState('all');
 const [priv,setPriv]=useState(false); const [uMap,setUMap]=useState<Record<string,any>>({});
 const cur=auth.currentUser;
 const my=posts.filter(p=>p.userId===cur?.uid); const vPosts=posts.filter(p=>p.userId===viewId);
 useEffect(()=>{return onSnapshot(query(collection(db,'posts'),orderBy('timestamp','desc')),s=>setPosts(s.docs.map(d=>({id:d.id,...d.data()} as Post))))},[]);
 useEffect(()=>{return onSnapshot(collection(db,'users'),s=>{const m:any={}; s.docs.forEach(d=>m[d.id]=d.data()); setUMap(m);})},[]);
 useEffect(()=>{ (async()=>{ if(!cur) return; const d=await getDoc(doc(db,'users',cur.uid)); if(d.exists()) setPriv(d.data().isPrivate||false); })(); },[cur]);
 const togglePriv=async()=>{ const v=!priv; setPriv(v); if(cur) await setDoc(doc(db,'users',cur.uid),{isPrivate:v,userName:cur?.email?.split('@')[0],userId:cur.uid},{merge:true}); };
 const like=async(p:Post)=>{ const l=p.likes?.includes(cur!.uid); await updateDoc(doc(db,'posts',p.id),{likes:l?arrayRemove(cur!.uid):arrayUnion(cur!.uid),likeCount:l?p.likeCount-1:p.likeCount+1}); };
 const comment=async(p:Post)=>{ if(!cmt.trim()) return; await updateDoc(doc(db,'posts',p.id),{comments:arrayUnion({id:Date.now().toString(),user:cur?.email?.split('@')[0],text:cmt})}); setCmt(''); };
 const del=async(p:Post)=>{ if(confirm('Delete?')) await deleteDoc(doc(db,'posts',p.id)); };
 const upload=async(e:any)=>{ const f=e.target.files[0]; if(!f) return; setUp(true); const fd=new FormData(); fd.append('file',f); fd.append('upload_preset',PRESET); const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD}/auto/upload`,{method:'POST',body:fd}); const d=await r.json(); setMedia(d.secure_url); setUp(false); };
 const create=async()=>{ if(!txt&&!media) return; await addDoc(collection(db,'posts'),{text:txt,image:ct!=='short'?media:'',videoUrl:ct==='short'||ct==='story'?media:'',userName:cur?.email?.split('@')[0],userId:cur?.uid,likeCount:0,likes:[],comments:[],mediaType:ct,timestamp:serverTimestamp()}); setTxt(''); setMedia(''); setShow(false); };
 const filt=posts.filter(p=>{ if(tab==='Feed') return p.mediaType==='feed'||!p.mediaType; if(tab==='Short') return p.mediaType==='short'; if(tab==='Watch') return p.mediaType==='watch'||(p.videoUrl&&p.mediaType!=='short'&&p.mediaType!=='story'); if(tab==='Story') return p.mediaType==='story'; return true; });
 const search=posts.filter(p=>p.userName.toLowerCase().includes(q.toLowerCase())||p.text.toLowerCase().includes(q.toLowerCase()));
 const openProfile=(id:string,name:string)=>{ setViewId(id); setViewName(name); setBot('UserProfile'); setPTab('all'); };
 const filterProfile=(list:Post[])=>{
   if(pTab==='all') return list;
   if(pTab==='photo') return list.filter(p=>p.image && (p.mediaType==='feed'||!p.mediaType));
   if(pTab==='video') return list.filter(p=>p.videoUrl || (p.mediaType==='feed'&&p.image));
   if(pTab==='short') return list.filter(p=>p.mediaType==='short');
   if(pTab==='watch') return list.filter(p=>p.mediaType==='watch'||(p.mediaType==='feed'&&p.videoUrl));
   if(pTab==='story') return list.filter(p=>p.mediaType==='story');
   return list;
 };
 return (
 <div className="min-h-screen flex justify-center bg-black"><div className="w-full max-w-[430px] h-[100dvh] relative overflow-hidden">
  <div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1200" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-black/60 backdrop-blur-[2px]"/></div>
  <div className="relative z-10 h-full flex flex-col p-3">
   <div className="bg-white/10 backdrop-blur-[25px] border border-white/20 rounded-[22px] px-4 py-3 flex justify-between items-center"><div className="flex gap-2 items-center"><div className="w-8 h-8 rounded-full bg-white text-black font-black flex items-center justify-center">⚡</div><p className="text-white font-black text-[12px]">OneFeedBD {priv?'🔒':'🌍'}</p></div><div className="flex gap-2"><button onClick={()=>setBot('Inbox')} className="w-8 h-8 rounded-full bg-white/10 text-white">✉</button><button onClick={()=>setBot('Settings')} className="w-8 h-8 rounded-full bg-white/10 text-white">⚙</button></div></div>
   <div className="flex-1 mt-3 overflow-hidden flex flex-col">
    {bot==='Home'&&<><div className="flex gap-1 p-1 rounded-full bg-white/10 border border-white/10">{['Feed','Short','Watch','Story'].map(k=><button key={k} onClick={()=>setTab(k)} className={`flex-1 py-2 rounded-full text-[10px] font-black ${tab===k?'bg-white text-black':'text-white/40'}`}>{k}</button>)}</div>
     <div className="flex-1 overflow-y-auto pb-28 mt-3 space-y-3">{filt.map(p=>{ const liked=p.likes?.includes(cur?.uid||''); return <div key={p.id} className="rounded-[20px] bg-white/10 backdrop-blur-xl border border-white/20 overflow-hidden"><div className="flex justify-between p-3"><div onClick={()=>openProfile(p.userId,p.userName)} className="flex gap-2 items-center cursor-pointer"><img src={`https://i.pravatar.cc/100?u=${p.userId}`} className="w-7 h-7 rounded-full"/><p className="text-white text-xs font-bold">{p.userName} {uMap[p.userId]?.isPrivate?'🔒':''}</p></div></div>{p.image&&<img src={p.image} className="w-full"/>}{p.videoUrl&&<video src={p.videoUrl} controls className="w-full"/>}<div className="p-3"><p className="text-white/80 text-[13px]">{p.text}</p><div className="flex gap-2 mt-3"><button onClick={()=>like(p)} className={`px-3 py-1.5 rounded-full text-[11px] ${liked?'bg-pink-500/20 text-pink-200':'bg-white/10 text-white/50'}`}>{liked?'❤️':'🤍'} {p.likeCount}</button><button onClick={()=>setOpenC(openC===p.id?null:p.id)} className="px-3 py-1.5 rounded-full bg-white/10 text-white/50 text-[11px]">💬 {p.comments?.length||0}</button></div>{openC===p.id&&<div className="mt-2 bg-black/30 rounded-xl p-2"><div className="space-y-1 mb-2">{p.comments?.map((c:any)=><p key={c.id} className="text-[11px] text-white/60"><b className="text-cyan-200">{c.user}:</b> {c.text}</p>)}</div><div className="flex gap-2"><input value={cmt} onChange={e=>setCmt(e.target.value)} placeholder="Comment" className="flex-1 bg-white/10 rounded-full px-3 py-1 text-xs text-white outline-none"/><button onClick={()=>comment(p)} className="px-3 rounded-full bg-white text-black text-xs">Send</button></div></div>}</div></div>})}</div></>}
    {bot==='Search'&&<div className="flex-1 pb-24"><div className="bg-white/10 border border-white/15 rounded-full px-4 py-2.5 flex gap-2"><span className="text-white/30">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name..." className="flex-1 bg-transparent text-sm text-white outline-none"/></div><div className="mt-4 space-y-2">{(q?search:posts).slice(0,12).map(p=><div key={p.id} onClick={()=>openProfile(p.userId,p.userName)} className="bg-white/10 border border-white/15 rounded-2xl p-3 flex gap-3 items-center cursor-pointer"><img src={`https://i.pravatar.cc/100?u=${p.userId}`} className="w-10 h-10 rounded-full"/><div><p className="text-white text-xs font-bold">{p.userName} {uMap[p.userId]?.isPrivate?'🔒':''}</p><p className="text-white/30 text-[11px]">{p.text.slice(0,25)}</p></div></div>)}</div></div>}
    {bot==='UserProfile'&&<div className="flex-1 overflow-y-auto pb-24"><button onClick={()=>setBot('Search')} className="mb-3 w-8 h-8 rounded-full bg-white/10 text-white">‹</button>{uMap[viewId||'']?.isPrivate && viewId!==cur?.uid ? <div className="bg-white/10 border border-white/20 rounded-[24px] p-8 text-center"><p className="text-4xl">🔒</p><p className="text-white font-black mt-3">Private Account</p></div> : <><div className="bg-white/10 border border-white/20 rounded-[24px] p-5 text-center"><img src={`https://i.pravatar.cc/150?u=${viewId}`} className="w-20 h-20 rounded-full mx-auto"/><h3 className="text-white font-black mt-2">{viewName}</h3><div className="grid grid-cols-3 gap-2 mt-4"><div className="bg-black/20 rounded-xl py-2"><p className="text-white font-bold">{vPosts.length}</p><p className="text-white/40 text-[8px]">POSTS</p></div><div className="bg-black/20 rounded-xl py-2"><p className="text-pink-300 font-bold">{vPosts.reduce((a,b)=>a+(b.likeCount||0),0)}</p><p className="text-white/40 text-[8px]">LIKES</p></div><div className="bg-black/20 rounded-xl py-2"><p className="text-cyan-300 font-bold">1.2K</p><p className="text-white/40 text-[8px]">FOLLOWERS</p></div></div></div><div className="mt-4 bg-white/10 border border-white/10 rounded-full p-1 flex gap-1 overflow-x-auto"><div className="flex gap-1 min-w-full">{[{id:'all',l:'All',i:'⊞'},{id:'photo',l:'Photos',i:'📸'},{id:'video',l:'Videos',i:'🎥'},{id:'short',l:'Shorts',i:'⚡'},{id:'watch',l:'Watch',i:'📺'},{id:'story',l:'Story',i:'💫'}].map(t=><button key={t.id} onClick={()=>setPTab(t.id)} className={`px-3 py-2 rounded-full text-[9px] font-black whitespace-nowrap ${pTab===t.id?'bg-white text-black':'text-white/40'}`}>{t.i} {t.l}</button>)}</div></div><div className="mt-3"><p className="text-white/20 text-[9px] tracking-widest mb-2">{pTab.toUpperCase()} • {filterProfile(vPosts).length} items</p><div className="grid grid-cols-3 gap-2">{filterProfile(vPosts).map(p=>p.image?<img key={p.id} src={p.image} className="h-24 w-full object-cover rounded-xl border border-white/10"/>:p.videoUrl?<video key={p.id} src={p.videoUrl} className="h-24 w-full object-cover rounded-xl border border-white/10"/>:<div key={p.id} className="h-24 bg-white/10 rounded-xl p-2 text-[10px] text-white/30">{p.text.slice(0,20)}</div>)}{filterProfile(vPosts).length===0&&<div className="col-span-3 text-center py-8"><p className="text-white/10 text-3xl">📭</p><p className="text-white/20 text-[11px] mt-2">No {pTab}</p></div>}</div></div></>}</div>}
    {bot==='Profile'&&<div className="flex-1 overflow-y-auto pb-24"><div className="bg-white/10 border border-white/20 rounded-[24px] p-5 text-center"><img src={`https://i.pravatar.cc/150?u=${cur?.uid}`} className="w-20 h-20 rounded-full mx-auto"/><h3 className="text-white font-black mt-2">{cur?.email?.split('@')[0]}</h3><p className="text-white/40 text-[10px]">{priv?'🔒 Private':'🌍 Public'} • Only you see all</p><div className="grid grid-cols-3 gap-2 mt-4"><div className="bg-black/20 rounded-xl py-3"><p className="text-white font-black text-lg">{my.length}</p><p className="text-white/40 text-[8px]">POSTS</p></div><div className="bg-black/20 rounded-xl py-3"><p className="text-pink-300 font-black text-lg">{my.reduce((a,b)=>a+(b.likeCount||0),0)}</p><p className="text-white/40 text-[8px]">LIKES</p></div><div className="bg-black/20 rounded-xl py-3"><p className="text-cyan-300 font-black text-lg">1.2K</p><p className="text-white/40 text-[8px]">FOLLOWERS</p></div></div></div>
     <div className="mt-4 bg-white/10 border border-white/10 rounded-full p-1 flex gap-1 overflow-x-auto"><div className="flex gap-1 min-w-full">{[{id:'all',l:'All',i:'⊞'},{id:'photo',l:'Photos',i:'📸'},{id:'video',l:'Videos',i:'🎥'},{id:'short',l:'Shorts',i:'⚡'},{id:'watch',l:'Watch',i:'📺'},{id:'story',l:'Story',i:'💫'}].map(t=><button key={t.id} onClick={()=>setPTab(t.id)} className={`px-3 py-2 rounded-full text-[9px] font-black whitespace-nowrap ${pTab===t.id?'bg-white text-black':'text-white/40'}`}>{t.i} {t.l}</button>)}</div></div>
     <div className="mt-3"><p className="text-white/20 text-[9px] tracking-widest mb-2">🔒 ONLY YOU • {pTab.toUpperCase()} • {filterProfile(my).length} items</p><div className="grid grid-cols-3 gap-2">{filterProfile(my).map(p=>p.image?<div key={p.id} className="relative group"><img src={p.image} className="h-28 w-full object-cover rounded-xl border border-white/10"/><button onClick={()=>del(p)} className="absolute top-1 right-1 w-5 h-5 rounded-full bg-black/60 text-white text-[9px] opacity-0 group-hover:opacity-100">✕</button></div>:p.videoUrl?<div key={p.id} className="relative group"><video src={p.videoUrl} className="h-28 w-full object-cover rounded-xl border border-white/10"/><button onClick={()=>del(p)} className="absolute top-1 right-1 w-5 h-5 rounded-full bg-black/60 text-white text-[9px] opacity-0 group-hover:opacity-100">✕</button></div>:<div key={p.id} className="h-28 bg-white/10 rounded-xl p-2 text-[10px] text-white/30">{p.text.slice(0,20)}</div>)}{filterProfile(my).length===0&&<div className="col-span-3 text-center py-8"><p className="text-white/10 text-3xl">📭</p><p className="text-white/20 text-[11px] mt-2">No {pTab} yet</p><p className="text-white/10 text-[9px]">Only you can see this</p></div>}</div></div>
    </div>}
    {bot==='Inbox'&&<div className="flex-1 pb-24"><h2 className="text-white font-black">Inbox</h2><div className="mt-3 space-y-2">{posts.slice(0,8).map(p=><div key={p.id} onClick={()=>openProfile(p.userId,p.userName)} className="bg-white/10 border border-white/15 rounded-2xl p-3 flex gap-3 cursor-pointer"><img src={`https://i.pravatar.cc/100?u=${p.userId}`} className="w-10 h-10 rounded-full"/><p className="text-white text-xs font-bold">{p.userName}</p></div>)}</div></div>}
    {bot==='Settings'&&<div className="flex-1 overflow-y-auto pb-28"><div className="flex gap-3 items-center mb-5"><button onClick={()=>setBot('Profile')} className="w-8 h-8 rounded-full bg-white/10 text-white">‹</button><h2 className="text-white font-black">Settings</h2></div><div className="space-y-3"><div className="bg-white/10 border border-white/15 rounded-[20px] p-4"><p className="text-white/30 text-[9px] tracking-widest mb-3">PRIVACY</p><div className="flex justify-between items-center"><div className="flex gap-3 items-center"><div className="w-9 h-9 rounded-full bg-white/10 flex items-center justify-center">{priv?'🔒':'🌍'}</div><div><p className="text-white text-xs font-bold">{priv?'Private':'Public'}</p><p className="text-white/40 text-[10px]">{priv?'Only you':'Anyone'}</p></div></div><button onClick={togglePriv} className={`w-12 h-6 rounded-full flex items-center p-1 ${priv?'bg-cyan-400 justify-end':'bg-white/20 justify-start'}`}><div className="w-4 h-4 rounded-full bg-white"/></button></div></div><div className="bg-white/10 border border-white/15 rounded-[20px] p-4"><p className="text-white/30 text-[9px] mb-3">ACCOUNT</p><div className="space-y-2 text-xs text-white/70"><p>👤 Edit Profile ›</p><p>🔒 Password ›</p><p>🚫 Blocked ›</p><p>🔔 Notifications ›</p><p>💧 Water Theme ›</p></div></div><button onClick={onLogout} className="w-full py-3 rounded-full bg-red-500/10 border border-red-500/20 text-red-300 text-xs font-black">LOGOUT</button></div></div>}
    <div className="absolute bottom-3 left-3 right-3 bg-white/10 backdrop-blur-[30px] border border-white/20 rounded-[28px] flex justify-around items-center py-2">{[{k:'Home',i:'⌂'},{k:'Search',i:'⌕'},{k:'Add',i:'+'},{k:'Inbox',i:'✉'},{k:'Profile',i:'◍'}].map(b=> b.k==='Add'? <button key={b.k} onClick={()=>setShow(true)} className="w-10 h-10 rounded-full bg-white text-black font-black">+</button>:<button key={b.k} onClick={()=>setBot(b.k)} className={`w-8 h-8 rounded-full ${bot===b.k?'bg-white/15 text-white':'text-white/30'}`}>{b.i}</button>)}</div>
   </div>
   {show&&<div className="absolute inset-0 z-50 bg-black/50 backdrop-blur-xl flex items-center justify-center p-4"><div className="w-full bg-white/15 border border-white/20 rounded-[20px] p-4"><div className="flex justify-between mb-3"><h3 className="text-white font-bold">Create</h3><button onClick={()=>setShow(false)} className="w-7 h-7 rounded-full bg-white/10 text-white/50">✕</button></div><div className="flex gap-1 mb-3 bg-black/20 p-1 rounded-full">{(['feed','short','story','watch'] as const).map(t=><button key={t} onClick={()=>setCt(t)} className={`flex-1 py-1.5 rounded-full text-[8px] font-black ${ct===t?'bg-white text-black':'text-white/40'}`}>{t.toUpperCase()}</button>)}</div><textarea value={txt} onChange={e=>setTxt(e.target.value)} placeholder="What's up?" className="w-full h-16 bg-white/10 border border-white/10 rounded-xl p-2 text-xs text-white outline-none"/><label className="block mt-2 py-2 rounded-xl bg-white/5 border border-dashed border-white/10 text-center text-xs text-white/40 cursor-pointer">{up?'Uploading...':media?'✅ Done':'📎 Media'}<input type="file" accept="video/*,image/*" onChange={upload} className="hidden"/></label><button onClick={create} className="w-full mt-3 py-2.5 rounded-full bg-white text-black font-black text-xs">PUBLISH</button></div></div>}
  </div></div></div>
 );
}
export default function App(){
 const [mode,setMode]=useState<'none'|'guest'|'auth'>('none'); const [chk,setChk]=useState(true);
 useEffect(()=>{ return onAuthStateChanged(auth,u=>{ if(u) setMode('auth'); else if(mode!=='guest') setMode('none'); setChk(false); }); },[]);
 if(chk) return <div className="min-h-screen bg-black flex items-center justify-center text-white/20">Loading...</div>;
 if(mode==='none') return <AuthPage onGuest={()=>setMode('guest')} />;
 return <FeedApp onLogout={async()=>{ await signOut(auth); setMode('none'); }} />;
  }
                    
